#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/zebra.conf ]; then
    cp $SNAP/etc/quagga/zebra.conf.default $SNAP_DATA/zebra.conf
fi
exec $SNAP/sbin/zebra \
    -f $SNAP_DATA/zebra.conf \
    --pid_file $SNAP_DATA/zebra.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

